version: '3.8'

networks:
  dev1:

services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass test
    volumes:
      - cache:/data
    networks:
      - dev1

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - dev1
    environment:
      - AWS_ACCESS_KEY_ID="blynn-dev"
      - AWS_SECRET_ACCESS_KEY="test"
      - AWS_SESSION_TOKEN="12345679"
      - AWS_DEFAULT_REGION=us-east-1


volumes:
  cache:
    driver: local
